bbb/cart/urls.py
from django.urls import path
from cart.views import *

app_name = 'cart'

urlpatterns = [
    path('', detail, name='detail'),
    path('add/<int:product_id>/', add, name='cart_add'),
    path('remove/<int:cart_id>/', remove, name='cart_remove'),
    path('mod/<int:cart_id>/', mod, name='cart_mod'),
    path('order/', order, name='order'),
]

bbb/member/urls.py
from django.urls import path
from member.views import *


app_name = 'member'
urlpatterns = [
    path('', MemListView.as_view(), name='list'),
    path('add/', MemAddView.as_view(), name='add'),
    path('detail/<int:pk>', MemDetailView.as_view(), name='detail'),
    path('edit/<int:pk>', MemEditView.as_view(), name='edit'),
    path('remove/<int:pk>', MemRemoveView.as_view(), name='remove'),
    path('login', login, name='login'),
    path('login_ok', login_ok, name='login_ok'),
    path('logout', logout, name='logout'),
    path('login_ajax', login_ajax, name='login_ajax'),
    #path('add', add, name='add'),
]

bbb/order/urls.py
from django.urls import path
from order.views import *
from order import views

app_name = 'order'

urlpatterns = [
    path('add', order_add, name='order_add'),
    path('list', order_list, name='order_list'),
    path('detail/<int:pk>', order_detail, name='order_detail'),
    #path('remove/<int:cart_id>/', remove, name='cart_remove'),
    #path('mod/<int:cart_id>/', mod, name='cart_mod'),
]

bbb/product/urls.py
from django.urls import path
from product.views import *
from product import views

app_name = 'product'
urlpatterns = [
    path('', ProdListView.as_view(), name='list'),
    #path('detail/<int:pk>', ProdDetailView.as_view(), name='detail'),
    #path('detail/<int:product_id>', views.datail, name='detail'),
    path('detail/<int:pk>', views.detail, name='detail'),
    path('add/', ProdAddView.as_view(), name='add'),
    path('like', like, name='like'),
    
]

bbb/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from shop import views
from django.conf.urls.static import static
from django.conf import settings
from product.forms import ProSearchForm

urlpatterns = [
    path('', views.home ,name='home'),    
    path('admin/', admin.site.urls),
    path('hot/', views.hot ,name='hot'),
    path('new/', views.new ,name='new'),    
    #path('accounts/', include('accounts.urls')),
    path('product/', include('product.urls')),
    path('cart/', include('cart.urls')),
    path('member/', include('member.urls')),
    path('order/', include('order.urls')),  
    path('accounts/', include('allauth.urls')),  
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bbb/cart/forms.py
from django import forms

# 클라이언트 화면에 입력 폼을 만들어주려고
# 클라이언트가 입력한 데이터에 대한 전처리

class AddProForm(forms.Form):
    amount = forms.IntegerField(initial=1,min_value=1, label="수량")

bbb/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
   <style>
      p{ color:blue;} 
      #id_amount {width : 50px;}
      .navbar navbar-expand-lg navbar-light bg-light{
        margin: 0 auto;
      }
      #navbar{
        margin: 0 auto;
      }
      .container-fluid {
        margin: 0 auto;
      }
      
   </style>
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</head>
<body>


<nav id="navbar" class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="btn btn-secondary btn-lg" href="{% url 'product:list' %}">SHOP</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <br/><a class="btn btn-outline-danger btn-sm" aria-current="page" href="{% url 'hot' %}">인기상품</a>
        </li>
        <li class="nav-item">
          <br/><p><a class="btn btn-outline-success btn-sm" href="{% url 'new' %}">신규상품</a></p>
        </li>
        <li class="nav-item dropdown">
          <br/><a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            마이쿠팡
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">주문목록</a></li>
            <li><a class="dropdown-item" href="#">취소/반품</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">찜리스트</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <br/><a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">전체</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
<p><br/>{% if request.session.member_id %} {{request.session.member_id}} 님이 로그인 하였습니다. 
<a href="{% url 'member:logout' %}" class="btn btn-light btn-sm">로그아웃</a>
<a href="{% url 'cart:detail' %}" class="btn btn-outline-info btn-sm">장바구니</a>
<a href="{% url 'order:order_list' %}" class="btn btn-outline-info btn-sm">주문목록</a> 
{% else %} <a href="{% url 'member:login' %}" class="btn btn-light btn-sm">로그인</a>
<a href="{% url 'member:add' %}" class="btn btn-light btn-sm" > 회원가입</a>    
        
    {% endif %}</p>
    </div>
  </div>
</nav>



<!--
<p>{% if request.session.member_id %} {{request.session.member_id}} 님이 로그인 하였습니다. <a href="{% url 'member:logout' %}">[로그아웃]</a>{% else %} <a href="">[로그인]</a> {% endif %}</p>
-->

{% block content %}
{% endblock %}
</div>
</body>
</html>

bbb/templates/home.html
{% extends 'base.html' %}

{% block title %} 상품리스트 {% endblock %}

{% block content %}  

 

<button type="button" class="btn btn-danger"><strong>인기상품</strong></button>

<div class="row"> 

    {% for prod in h_list %}

	<div class="col-2">

		<div class="card">

		{% if prod.pro_img %}<img class="cart-img-top"  src="{{prod.pro_img.url}}" style="width:100%;">{% endif %}

		</div>

		 <div class="card-body">

		<a href="{% url 'product:detail' pk=prod.id %}">{{ prod.pro_name }}</a> <br/> <strong class = "price-value">가격 : {{ prod.pro_price }}원</strong> <a href="">[수정]</a> <a href="">[삭제]</a>

		 </div>

	</div>

    {% endfor %}

 

 

 
	
	<div class ="body">

		<br/><button type="button" class="btn btn-success"><strong>신규상품</strong></button>

	</div>

	<div class="row">  

    {% for prod in n_list %}

		<div class="col-2">

			<div class="card">

		{% if prod.pro_img %}<img class="cart-img-top"  src="{{prod.pro_img.url}}" style="width:100%;">{% endif %}

			</div>

			<div class="card-body">

		<a href="{% url 'product:detail' pk=prod.id %}">{{ prod.pro_name }}</a> :: 가격 : {{ prod.pro_price }}원 <a href="">[수정]</a> <a href="">[삭제]</a>
			
		</div>

	</div>

    {% endfor %}

 

 

 

</div>
{% endblock %}

bbb/templates/hot.html
{% extends 'base.html' %}

{% block title %} 상품리스트 {% endblock %}

{% block content %}  

 

<button type="button" class="btn btn-danger"><strong>인기상품</strong></button>
<div class="row"> 
    {% for prod in h_list %}
	<div class="col-3">
		 <div class="card">
		{% if prod.pro_img %}<img class="cart-img-top"  src="{{prod.pro_img.url}}" style="width:100%;">{% endif %}
		</div>
		<div class="card-body">
		<a href="{% url 'product:detail' pk=prod.id %}">{{ prod.pro_name }}</a> :: 가격 : {{ prod.pro_price }}원 <a href="">[수정]</a> <a href="">[삭제]</a>

		</div>

	</div>

    {% endfor %}



{% endblock %}

bbb/templates/new.html
{% extends 'base.html' %}

{% block title %} 상품리스트 {% endblock %}

{% block content %}  

 

<button type="button" class="btn btn-success"><strong>신규상품</strong></button>
<div class="row"> 
    {% for prod in n_list %}
	<div class="col-3">
		 <div class="card">
		{% if prod.pro_img %}<img class="cart-img-top"  src="{{prod.pro_img.url}}" style="width:100%;">{% endif %}
		</div>
		<div class="card-body">
		<a href="{% url 'product:detail' pk=prod.id %}">{{ prod.pro_name }}</a> :: 가격 : {{ prod.pro_price }}원 <a href="">[수정]</a> <a href="">[삭제]</a>

		</div>

	</div>

    {% endfor %}



{% endblock %}