bbb/cart/urls.py
from django.urls import path
from cart.views import *

app_name = 'cart'

urlpatterns = [
    path('', detail, name='detail'),
    path('add/<int:product_id>/', add, name='cart_add'),
    path('remove/<int:cart_id>/', remove, name='cart_remove'),
    path('mod/<int:cart_id>/', mod, name='cart_mod'),
    path('order/', order, name='order'),
]

bbb/product/urls.py
from django.urls import path
from product.views import *
from product import views

app_name = 'product'
urlpatterns = [
    path('', ProdListView.as_view(), name='list'),
    #path('detail/<int:pk>', ProdDetailView.as_view(), name='detail'),
    #path('detail/<int:product_id>', views.datail, name='detail'),
    path('detail/<int:pk>', views.detail, name='detail'),
    path('add/', ProdAddView.as_view(), name='add'),
    path('like', like, name='like'),
    
]

bbb/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from shop import views
from django.conf.urls.static import static
from django.conf import settings
from product.forms import ProSearchForm

urlpatterns = [
    path('', views.home ,name='home'),    
    path('admin/', admin.site.urls),
    path('hot/', views.hot ,name='hot'),
    path('new/', views.new ,name='new'),    
    #path('accounts/', include('accounts.urls')),
    path('product/', include('product.urls')),
    path('cart/', include('cart.urls')),
    path('member/', include('member.urls')),
    path('order/', include('order.urls')),  
    path('accounts/', include('allauth.urls')),  
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bbb/product/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone

# Create your models here.

class Product(models.Model):
    pro_name = models.CharField('상품명',max_length=200)
    pro_price = models.IntegerField('가격')
    pro_stock = models.IntegerField('재고수량',default=100)
    pro_img = models.ImageField('상품이미지',upload_to='products/%Y/%m/%d', blank=True)
    pro_desc = models.TextField('상품설명',blank=True)
    pro_hot = models.BooleanField('인기상품',default=False)
    pro_new = models.BooleanField('신규상품',default=False)
    pro_display = models.BooleanField('화면표시',default=True)
    pro_day = models.DateField('등록일',default=timezone.now)
    pro_like = models.IntegerField(default=0)

    def __str__(self):
        return self.pro_name

    def get_absolute_url(self):
        return reverse('product:detail', args=[self.id])

bbb/product/forms.py
from django import forms

# 클라이언트 화면에 입력 폼을 만들어주려고
# 클라이언트가 입력한 데이터에 대한 전처리

class ProSearchForm(forms.Form):        
    search_word = forms.CharField(label='상품 검색')

bbb/product/views.py
# Create your views here.
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse, reverse_lazy
from django.db.models import Q
from product.models import Product
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from member.models import Mem

from django.conf import settings
import os
from cart.forms import AddProForm
from product.forms import ProSearchForm
try:
    from django.utils import simplejson as json
except ImportError:
    import json


class ProdListView(ListView):
    model = Product
    #queryset = Product.objects.filter(pro_display=1)
    ## 모델명(소문자)_list.html
    paginate_by = 3
    template_name = 'product/list.html'
    ## object_list 로 객체 반환
    
# class ProdDetailView(DetailView):
#     model = Product
#     ## 모델명(소문자)_detail.html
#     template_name = 'product/detail.html'
#     ## object 로 객체 반환
    
def detail(request, pk):
    product = get_object_or_404(Product, id=pk)
    add_to_cart = AddProForm()
    return render(request, 'product/detail.html', {'product':product, 'add_to_cart':add_to_cart})

def search(request):

    form = ProSearchForm(request.POST)
    if form.is_valid():
            cd = form.cleaned_data
            search_item = cd['search_word']
            
    product_list = Product.objects.filter(Q(pro_name__contains=search_item) & Q(pro_display=1))
    return render(request, 'product/search.html', {'product_list':product_list, 'search_item':search_item})

class ProdAddView(CreateView):
    model = Product
    fields = ['Mem_id','Mem_name', 'Mem_pwd']
    success_url = reverse_lazy('product:list')
    template_name = 'product/add.html'
    
def like(request):
    if request.method == 'POST':
        product_id = request.POST['pk']
        product = Product.objects.get(pk = product_id)
        product.pro_like +=1
        product.save()
        message = 'You liked this'
    context = {'likes_count' : product.pro_like, 'message' : message}

    return HttpResponse(json.dumps(context), content_type='application/json')


# def add(request):
#     form=Mem()    
#     if request.method == "POST":
#         
#         if request.FILES:
#             form.Mem_img = request.FILES['upload_files']
#         else:
#            form.Mem_img = ''
# 
#         form.Mem_id=request.POST['mem_id']
#         form.Mem_name=request.POST['mem_name']
#         form.Mem_pwd=request.POST['mem_pwd']
#         form.save()
#         return HttpResponseRedirect(reverse('member:list'))
# 
#     else:
#         return render(request, 'member/add2.html')

bbb/product/templates/product/add.html
<form action="" method="post">
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="회원가입" />
</form>

bbb/product/templates/product/detail.html
{% extends 'base.html' %}

{% block title %} 상품 상세보기 {% endblock %}

{% block content %}
<head>
	<style>
		.display-6 {
		font-weight : bold;
		}
		.price-value {
			color: #AE0000;
			font-size: 20px;
			font-family: Tahoma;
		}
		h5{
			color: black;
		}
		.row{
			width: 980px;
			margin: 0 auto;
		}
		.tab .tab-titles {
			border-top: 2px solid #555;
			border-bottom: 1px solid #ccc;
			border-left: 1px solid #ccc;
			list-style-type: none;
			font-size: 0;

			top: 0;
			width: 980px;
			margin: 0 auto;
			-webkit-user-select: none;
			-ms-user-select: none;
			user-select: none;
		}
		ul {
			display: block;
			list-style-type: disc;
			margin-block-start: 1em;
			margin-block-end: 1em;
			margin-inline-start: 0px;
			margin-inline-end: 0px;
			padding-inline-start: 40px;
		}
		.tab .tab-titles>li.active {
			margin-bottom: -2px;
			background: #ffffff;
			border-bottom: 1px solid #fff;
			color: #111;
		}
		.tab .tab-titles>li {
			display: inline-block;
			padding: 15px 20px 14px;
			width: 25%;
			border-right: 1px solid #ccc;
			background-color: #fafafa;
			text-align: center;
			color: #555;
			font-weight: bold;
			font-size: 16px;
			box-sizing: border-box;
			cursor: pointer;
		}
		
	</style>
	
</head>

<script>

$(document).ready(function(){

	$('.like').click(function(){
	  var pk = $(this).attr('name')
	  //alert(pk);
	  $.ajax({	  
		  url: "{% url 'product:like' %}",
		  type: 'post',
		  data: {
			pk: pk, 
			csrfmiddlewaretoken: '{{ csrf_token }}'
			},
		  success: function(response){
			
			$('#count'+ pk).html("count : "+ response.likes_count);
		  },
		  error:function(xhr){
			alert(xhr.status);
		  }

	  });
	})

});
</script>

    <div class="row">
        <div class="col-4">
            <img src="{{product.pro_img.url}}" width="100%">
        </div>
        <div class="col">
            <h1 class="display-6">{{product.pro_name}}</h1>
			<p><span class="badge badge-secondary">Price</span><strong class ="price-value">{{product.pro_price}}</strong></p>

            <form action="{% url 'cart:cart_add' product_id=product.id%}" method="post">
                {{add_to_cart}}
                {% csrf_token %}
            <input type="submit" class="btn btn-primary btn-sm" value="장바구니담기">
            </form>

            <h5>{{product.pro_desc|linebreaks}}</h5>
			<input type="button" class="like" name="{{ product.id }}" value="Like">
			<p id="count{{ product.id }}">count : {{ product.pro_like }}</p>
        </div>
    </div>

	<div id="btfTab" class="tab">
		<ul class="tab-titles">
			<li name="detail" class="active">상품상세</li>
			<li name="review">
				상품평
				<span class="product-tab-review-count">(7,819)</span>
			</li>
			<li name="qna">상품문의</li>
			<li name="etc">배송/교환/반품 안내</li>
		</ul>

		<footer id ="footer" class = "footer_new">
			<div class="footer-layer1 is-narrowed">
				<a href="" target="_blank">회사소개</a>
				<a href="" target="_blank">인재채용</a>
				<a href="" target="_blank">공지사항</a>
				<a href="" target="_blank">이용약관</a>
				<a href="" target="_blank">개인정보처리방침</a>
			</div>
			<div class="footer-layer2">
				<h1>
					<a href="/" title="SHOP">SHOP</a>
				</h1>
				<div class="footer-content">
					<address>
						" 상호명 및 호스팅 서비스 제공 : 쿠팡(주)"
						<br>
						" 대표이사 : 강한승,박대준"
						<br>
						"서울시 송파구 송파대로 570 "
						<br>
						" 사업자 등록번호 : 120-88-00767"
						<br>
						" 통신판매업신고 : 2017-서울송파-0680"
						<br>
						<a href="" target="_black" class="licensee" title="사업자정보확인">사업자정보확인</a>
					</address>
					<div class="contact-into">
						<a href="" class="call-center" title="365 고객센터">
							<strong>365고객센터</strong>
							"| 전자금융거래분쟁처리담당"
							<br>
							<em>1577-7011</em>
							"서울시 송파구 송파대로 570"
							<br>
							<span class="contact-fax">email : help@coupang.com
							</span>
						</a>
					</div>
					<p class="safe-service">
						<strong>우리은행 채무지급보증 안내</strong>
						<br>
						<span>
							"당사는 고객님이 현금 결제한 금액에 대해"
							<br>
							"우리은행과 채무지급보증 계약을 체결하여"
							<br>
							"안전거래를 보장하고 있습니다."
							<br>
						</span>
						<a href="javascript:;" id="serviceCheck" class="service-check" title="서비스 가입사실 확인">서비스 가입사실 확인</a>
					</p>
				</div>
			</div>
			<div class="footer-layer3 slide-unit">
				<div class="certification-list" style="width: 968px;height: 80px; margin: 0 auto; background: url(//static.coupangcdn.com/image/coupang/common/footer_asset_v10.png) no-repeat; background-position: -44px -92px; position: relative;">	</div>
			</div>
			<div class="footer-layer4">
				<div class="coupang-copyright">
					<p class="info" style="padding-top:9px">
						"사이버몰 내 판매되는 상품 중에는 쿠팡에 등록한 개별 판매자가 판매하는 마켓플레이스(오픈마켓) 상품이 포함되어 있습니다. "
						<br>
						" 마켓플레이스(오픈마켓) 상품의 경우 쿠팡은 통신판매중개자이며 통신판매의 당사자가 아닙니다. "
						<br>
						"쿠팡은 마켓플레이스(오픈마켓) 상품, 거래정보 및 거래 등에   대하여 책임을 지지 않습니다. "
						<br>
						" 쿠팡은 소비자 보호와 안전거래를 위해 신뢰관리센터(CM112@coupang.com)를 운영하고 있으며, 관련 분쟁이 발생할 경우 별도의 분쟁  처리절차에 의거 분쟁이 처리됩니다."
						<br>
						" Copyright © Coupang Corp. 2010-2021 All Rights Reserved.
						"
					</p>
					<ul class="sns-link">
						<li>
							<a href="https://www.facebook.com/Coupang.korea" targer="_blank" class="facebook" title="쿠팡 페이스북">쿠팡 페이스북</a>
						</li>
						<li>
							<a href="https://news.coupang.com/" target="_blank" class="blog" title="쿠팡 뉴스룸">쿠팡 뉴스룸</a>
						</li>
						<li>
							<a href="https://www.instagram.com/coupang" target="_blank" class="instagram" title="쿠팡 인스타그램">쿠팡 인스타그램</a>
						</li>
					</ul>
				</div>
			</div>
		</footer>
	</div>



{% endblock %}

bbb/product/templates/product/list.html
{% extends 'base.html' %}
{% load humanize %}
{% block title %} 상품리스트 {% endblock %}
{% block content %}  

<div class="row">  
    {% for prod in object_list %}
	<div class="col-3">
		 <div class="card">
		{% if prod.pro_img %}<a href="{% url 'product:detail' pk=prod.id %}"><img class="cart-img-top"  src="{{prod.pro_img.url}}" style="width:100%;"></a>{% endif %}
		</div>
		<div class="card-body">
		<a href="{% url 'product:detail' pk=prod.id %}">{{ prod.pro_name }}</a> <br/> 가격 : {{ prod.pro_price|intcomma  }}원</a>
		</div>
	</div>
    {% endfor %}
</div>

{{ page_obj }}
<nav aria-label="...">
<ul class="pagination">
{% if page_obj.has_previous %}
	<li class="page-item">
		<a class="page-link" href="?page=1">First</a>
    </li>
    <li class="page-item">
		<a class="page-link" href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
	</li>
{% endif %}
    <li class="page-item active" aria-current="page">
		<a class="page-link" href="#">{{ page_obj.number }}</a>
    </li>
{% if page_obj.has_next %}
    <li class="page-item">
		<a class="page-link" href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
	</li>
    <li class="page-item">
	<a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
    </li>
{% endif %}
</ul>
</nav>


{% endblock %}