bbb/cart/urls.py
from django.urls import path
from cart.views import *

app_name = 'cart'

urlpatterns = [
    path('', detail, name='detail'),
    path('add/<int:product_id>/', add, name='cart_add'),
    path('remove/<int:cart_id>/', remove, name='cart_remove'),
    path('mod/<int:cart_id>/', mod, name='cart_mod'),
    path('order/', order, name='order'),
]

bbb/member/urls.py
from django.urls import path
from member.views import *


app_name = 'member'
urlpatterns = [
    path('', MemListView.as_view(), name='list'),
    path('add/', MemAddView.as_view(), name='add'),
    path('detail/<int:pk>', MemDetailView.as_view(), name='detail'),
    path('edit/<int:pk>', MemEditView.as_view(), name='edit'),
    path('remove/<int:pk>', MemRemoveView.as_view(), name='remove'),
    path('login', login, name='login'),
    path('login_ok', login_ok, name='login_ok'),
    path('logout', logout, name='logout'),
    path('login_ajax', login_ajax, name='login_ajax'),
    #path('add', add, name='add'),
]

bbb/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from shop import views
from django.conf.urls.static import static
from django.conf import settings
from product.forms import ProSearchForm

urlpatterns = [
    path('', views.home ,name='home'),    
    path('admin/', admin.site.urls),
    path('hot/', views.hot ,name='hot'),
    path('new/', views.new ,name='new'),    
    #path('accounts/', include('accounts.urls')),
    path('product/', include('product.urls')),
    path('cart/', include('cart.urls')),
    path('member/', include('member.urls')),
    path('order/', include('order.urls')),  
    path('accounts/', include('allauth.urls')),  
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bbb/member/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Mem(models.Model):
    Mem_id = models.CharField('회원아이디', max_length=200, unique=True)
    Mem_pwd = models.CharField('회원비밀번호', max_length=200)
    Mem_name = models.CharField('회원 이름', max_length=200)
    Mem_tel = models.CharField('연락처', max_length=200, null=True)
    Mem_addr = models.CharField('주소', max_length=200, null=True)
    Mem_img = models.FileField('사진',upload_to='member/%Y-%m-%d', null=True, blank='True', default='')

    def __str__(self):
        return self.Mem_id

    def get_absolute_url(self):
        return reverse('member:detail', args=[self.id])
    
    # def delete(self, *args, **kargs):
    #     os.remove(os.path.join(settings.MEDIA_ROOT, self.Mem_img.name))
    #     super(Mem, self).delete(*args, **kargs)

bbb/member/views.py
#from django.shortcuts import render

# Create your views here.

from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse, reverse_lazy
from django.db.models import Q
from member.models import Mem
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from django.core.files.storage import FileSystemStorage
try:
    from django.utils import simplejson as json
except ImportError:
    import json
# from django.conf import settings
# import os

class MemListView(ListView):
    model = Mem
    ## 모델명(소문자)_list.html
    template_name = 'member/list.html'
    ## object_list 로 객체 반환
    

class MemAddView(CreateView):
    model = Mem
    fields = ['Mem_id','Mem_name', 'Mem_pwd', 'Mem_img']
    success_url = reverse_lazy('product:list')
    template_name = 'member/add.html'

# def add(request):
#     form=Mem()    
#     if request.method == "POST":
#         
#         if request.FILES:
#             form.Mem_img = request.FILES['upload_files']
#         else:
#            form.Mem_img = ''
# 
#         form.Mem_id=request.POST['mem_id']
#         form.Mem_name=request.POST['mem_name']
#         form.Mem_pwd=request.POST['mem_pwd']
#         form.save()
#         return HttpResponseRedirect(reverse('member:list'))
# 
#     else:
#         return render(request, 'member/add2.html')
# 
# def edit(request, pk):
# 
#     if request.method == "POST":
# 
#         form = Mem.objects.get(pk=pk)
#         if request.FILES:
#             ## 업로할 파일이 있으면
#             if form.Mem_img.name:## 기존에 파일이 있으면 삭제 폴더에서 삭제ㅐ
#                 os.remove(os.path.join(settings.MEDIA_ROOT, form.Mem_img.name))
#                 
#             form.Mem_img = request.FILES['upload_files']
#         else:
#            pass
#         
#         form.Mem_id=request.POST['mem_id']
#         form.Mem_name=request.POST['mem_name']
#         form.Mem_pwd=request.POST['mem_pwd']
#         form.save()
#         return HttpResponseRedirect(reverse('member:detail', args=(pk,)))
# 
#     else:
#         member = get_object_or_404(Mem, pk=pk)
#         return render(request, 'member/edit2.html', {'member': member})  


class MemDetailView(DetailView):
    model = Mem
    ## 모델명(소문자)_detail.html
    template_name = 'member/detail.html'
    ## object 로 객체 반환

class MemEditView(UpdateView):
    model = Mem
    fields = ['Mem_name', 'Mem_pwd','Mem_img']
    template_name = 'member/edit.html'
    ##success_url = reverse_lazy('member:list')


class MemRemoveView(DeleteView):
    model = Mem
    success_url = reverse_lazy('member:list')
    
def login(request):

    if request.method == "POST":

        m = Mem.objects.get(Mem_id=request.POST['mem_id'])
        if m.Mem_pwd == request.POST['mem_pwd']:
            ## 일치 하는 값이 있으면 로그인 처리
            request.session['member_id'] = m.Mem_id
            #request.session.set_expiry()
            print(request.session.get_expiry_date())
            return HttpResponseRedirect(reverse('product:list'))
        else:
            return HttpResponse("Your username and password didn't match.")

        #return HttpResponseRedirect(reverse('member:login_ok'))

    else:
        return render(request, 'member/login.html')

def login_ajax(request):

    if request.method == "POST":

        print(request.POST['mem_id'])
        m = Member.objects.get(mem_id=request.POST['mem_id'])
        if m.mem_pwd == request.POST['mem_pwd']:
            request.session['member_id'] = m.mem_id
            context = {'id' : m.mem_id, 'name' : m.mem_name}
        else:
            context = {'msg': '일치하는 정보가 없습니다'}
        
        return HttpResponse(json.dumps(context, ensure_ascii=False), content_type='application/json')

    else:
        return render(request, 'member/login_ajax.html')

def login_ok(request):

    member = Mem.objects.get(Mem_id=request.session['member_id'])
    return render(request, 'member/login_ok.html', {'member': member})


def logout(request):

    if request.session['member_id']:
        #request.session.flush()
        del request.session['member_id']
        return HttpResponseRedirect(reverse('product:list'))
    else:
        pass

bbb/member/templates/member/add.html
{% extends 'base.html' %}
{% block title %} 회원리스트 {% endblock %}
{% block content %}

{% load static %}
<br>
<img src="{% static 'member/t1.jpg' %}" alt="My image" width="300">
<br>
<form action="" method="post">
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="회원가입" />
</form>
{% endblock %}

bbb/member/templates/member/add2.html
<form action="" method="post" enctype="multipart/form-data">
{% csrf_token %}
아이디 : <input type="text" name="mem_id"><br />
비밀번호 : <input type="text" name="mem_pwd"><br />
이름 : <input type="text" name="mem_name"><br />
첨부파일 : <input type="file" name="upload_files"><br />
<input type="submit" value="회원가입" />
</form>

bbb/member/templates/member/detail.html
<h1><회원정보></h1>
<h3>ID : {{ object.Mem_id }} 이름 : {{ object.Mem_name }}</h3>
{% load static %}
<img src="{% static 'member/t1.jpg' %}" alt="My image" width="200">

<a href="{% url 'member:list' %}"> 홈 화면으로 이동 </a>

bbb/member/templates/member/edit.html
<form action="" method="post">
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="회원정보수정" />
</form>

bbb/member/templates/member/edit2.html
<form action="" method="post" enctype="multipart/form-data">
{% csrf_token %}
아이디 : <input type="text" name="mem_id" value="{{member.Mem_id}}"><br />
비밀번호 : <input type="text" name="mem_pwd" value="{{member.Mem_pwd}}"><br />
이름 : <input type="text" name="mem_name" value="{{member.Mem_name}}"><br />
{% if member.Mem_img %}<img src="{{ member.Mem_img.url }}" width="200"><br />{% endif %}
첨부파일 : <input type="file" name="upload_files"><br />
<input type="submit" value="회원정보수정" />
</form>

bbb/member/templates/member/list.html
{% extends 'base.html' %}
{% block title %} 회원리스트 {% endblock %}
{% block content %}
<h2><a href="{% url 'member:add' %}">회원가입</a></h2>
<h3>회원목록</h3>
    <ul>
    {% for member in object_list %}
        <li>{% if member.Mem_img %}<img src="{{ member.Mem_img.url }}" width="100">{% endif %}<a href="{% url 'member:detail' pk=member.id %}">ID : {{ member.Mem_id }}</a> - 이름 : {{ member.Mem_name }} <a href="{% url 'member:edit' pk=member.id %}">[수정]</a> <a href="{% url 'member:remove' pk=member.id %}">[삭제]</a></li>
    {% endfor %}
    </ul>
{% load static %}
<img src="{% static 'member/t1.jpg' %}" alt="My image" width="100">
{% endblock %}

bbb/member/templates/member/login.html
{% extends 'base.html' %}
{% block title %} 회원리스트 {% endblock %}
{% block content %}

<form action="" method="post" enctype="multipart/form-data">
{% csrf_token %}
아이디 : <input type="text" name="mem_id" value="{{member.Mem_id}}"><br />
비밀번호 : <input type="password" name="mem_pwd" value="{{member.Mem_pwd}}"><br />

<input type="submit" value="로그인" />
</form>
{% endblock %}

bbb/member/templates/member/login_ajax.html
{% extends 'base.html' %}
{% load humanize %}
{% block title %}
Shopping Cart
{% endblock %}

{% block content %}
	<script>

   $(document).ready(function(){
      $("button").click(myFunction);
   });

	function myFunction(){
		
         $.ajax({

			url:"{% url 'member:login_ajax' %}",
			type: "post",
			data:{

				mem_id: $("#id").val(),
				mem_pwd: $("#pwd").val(),
				csrfmiddlewaretoken: '{{ csrf_token }}'
			
			},
			success:function(data){
				
				if (data.msg){
					$("#div1").prepend(data.msg+"<br />");
				}else{
					var txt = "아이디 "+data.id+ " - 이름 " +data.name+ " 정상적으로 로그인 하였습니다";
					$("#div1").html(txt);
				}
               
			},error:function(xhr){
               
			   alert(xhr.status);
			}

         });

	}
</script>
<div class="container-sm d-grid gap-3" style="max-width: 500px;">

	<div id="div1">
	아이디<input type="text" name="mem_id" id="id"><br />
	비밀번호<input type="text" name="mem_pwd" id="pwd"><br />
	<button>로그인하기</button>
	<div>

</div>
{% endblock %}

bbb/member/templates/member/mem_confirm_delete.html
<form action="" method="post">
{% csrf_token %}
{{ object }}를 정말 삭제 하겠습니까?
<input type="submit" value="삭제하기" />
</form>